name: Volt Compiler Build & Release

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    name: Build Volt Core (${{ matrix.target }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - aarch64-linux-android
          - x86_64-unknown-linux-gnu
          - aarch64-unknown-linux-gnu

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Rust Toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Build Volt Release Binary
        run: cargo build --target ${{ matrix.target }} --release

      - name: Upload Binary Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: volt-compiler-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/volt_compiler
